
-- --- AUDIT LOG: 2026-03-25 01:34:07 ---
CREATE TABLE "account_dimension" (id SERIAL NOT NULL, "create_uid" int4, "write_uid" int4, "name" VARCHAR NOT NULL, "code" VARCHAR NOT NULL, "create_date" timestamp, "write_date" timestamp, PRIMARY KEY(id)); COMMENT ON TABLE "account_dimension" IS 'Chiều phân tích'; COMMENT ON COLUMN "account_dimension"."create_uid" IS 'Created by'; COMMENT ON COLUMN "account_dimension"."write_uid" IS 'Last Updated by'; COMMENT ON COLUMN "account_dimension"."name" IS 'Tên chiều PT'; COMMENT ON COLUMN "account_dimension"."code" IS 'Mã chiều PT'; COMMENT ON COLUMN "account_dimension"."create_date" IS 'Created on'; COMMENT ON COLUMN "account_dimension"."write_date" IS 'Last Updated on';
ALTER TABLE "account_dimension" ADD CONSTRAINT "account_dimension_check_code_uniq" unique(code);
COMMENT ON CONSTRAINT "account_dimension_check_code_uniq" ON "account_dimension" IS 'unique(code)';
ALTER TABLE "account_dimension" ADD FOREIGN KEY ("create_uid") REFERENCES "res_users"("id") ON DELETE set null;
ALTER TABLE "account_dimension" ADD FOREIGN KEY ("write_uid") REFERENCES "res_users"("id") ON DELETE set null;

-- --- AUDIT LOG: 2026-03-25 01:54:51 ---
CREATE TABLE "business_segment" (id SERIAL NOT NULL, "create_uid" int4, "write_uid" int4, "name" VARCHAR NOT NULL, "code" VARCHAR NOT NULL, "create_date" timestamp, "write_date" timestamp, PRIMARY KEY(id)); COMMENT ON TABLE "business_segment" IS 'Mảng kinh doanh'; COMMENT ON COLUMN "business_segment"."create_uid" IS 'Created by'; COMMENT ON COLUMN "business_segment"."write_uid" IS 'Last Updated by'; COMMENT ON COLUMN "business_segment"."name" IS 'Tên mảng KD'; COMMENT ON COLUMN "business_segment"."code" IS 'Mã mảng KD'; COMMENT ON COLUMN "business_segment"."create_date" IS 'Created on'; COMMENT ON COLUMN "business_segment"."write_date" IS 'Last Updated on';
ALTER TABLE "business_segment" ADD CONSTRAINT "business_segment_check_code_uniq" unique(code);
COMMENT ON CONSTRAINT "business_segment_check_code_uniq" ON "business_segment" IS 'unique(code)';
ALTER TABLE "business_segment" ADD FOREIGN KEY ("create_uid") REFERENCES "res_users"("id") ON DELETE set null;
ALTER TABLE "business_segment" ADD FOREIGN KEY ("write_uid") REFERENCES "res_users"("id") ON DELETE set null;

-- --- AUDIT LOG: 2026-03-25 02:33:36 ---
CREATE TABLE "dimension_account_rel" ("dimension_id" INTEGER NOT NULL,
                                          "account_id" INTEGER NOT NULL,
                                          PRIMARY KEY("dimension_id", "account_id"));
                    COMMENT ON TABLE "dimension_account_rel" IS 'RELATION BETWEEN account_dimension AND account_account';
                    CREATE INDEX ON "dimension_account_rel" ("account_id", "dimension_id");
ALTER TABLE "account_dimension" ADD COLUMN "company_id" int4 ; COMMENT ON COLUMN "account_dimension"."company_id" IS 'Công ty áp dụng';
ALTER TABLE "account_dimension" ALTER COLUMN "code" DROP NOT NULL;
CREATE TABLE "account_dimension_value" (id SERIAL NOT NULL, "dimension_id" int4, "create_uid" int4, "write_uid" int4, "code" VARCHAR, "name" VARCHAR NOT NULL, "create_date" timestamp, "write_date" timestamp, PRIMARY KEY(id)); COMMENT ON TABLE "account_dimension_value" IS 'account.dimension.value'; COMMENT ON COLUMN "account_dimension_value"."dimension_id" IS 'Thuộc chiều phân tích'; COMMENT ON COLUMN "account_dimension_value"."create_uid" IS 'Created by'; COMMENT ON COLUMN "account_dimension_value"."write_uid" IS 'Last Updated by'; COMMENT ON COLUMN "account_dimension_value"."code" IS 'Mã'; COMMENT ON COLUMN "account_dimension_value"."name" IS 'Tên giá trị'; COMMENT ON COLUMN "account_dimension_value"."create_date" IS 'Created on'; COMMENT ON COLUMN "account_dimension_value"."write_date" IS 'Last Updated on';
ALTER TABLE "account_dimension" ALTER COLUMN "company_id" SET NOT NULL;
ALTER TABLE "dimension_account_rel" ADD FOREIGN KEY ("dimension_id") REFERENCES "account_dimension"("id") ON DELETE cascade;
ALTER TABLE "dimension_account_rel" ADD FOREIGN KEY ("account_id") REFERENCES "account_account"("id") ON DELETE cascade;
ALTER TABLE "account_dimension" ADD FOREIGN KEY ("company_id") REFERENCES "res_company"("id") ON DELETE restrict;
ALTER TABLE "account_dimension_value" ADD FOREIGN KEY ("dimension_id") REFERENCES "account_dimension"("id") ON DELETE cascade;
ALTER TABLE "account_dimension_value" ADD FOREIGN KEY ("create_uid") REFERENCES "res_users"("id") ON DELETE set null;
ALTER TABLE "account_dimension_value" ADD FOREIGN KEY ("write_uid") REFERENCES "res_users"("id") ON DELETE set null;

-- --- AUDIT LOG: 2026-03-25 02:34:20 ---
CREATE TABLE "dimension_account_rel" ("dimension_id" INTEGER NOT NULL,
                                          "account_id" INTEGER NOT NULL,
                                          PRIMARY KEY("dimension_id", "account_id"));
                    COMMENT ON TABLE "dimension_account_rel" IS 'RELATION BETWEEN account_dimension AND account_account';
                    CREATE INDEX ON "dimension_account_rel" ("account_id", "dimension_id");
ALTER TABLE "account_dimension" ADD COLUMN "company_id" int4 ; COMMENT ON COLUMN "account_dimension"."company_id" IS 'Công ty áp dụng';
ALTER TABLE "account_dimension" ALTER COLUMN "code" DROP NOT NULL;
CREATE TABLE "account_dimension_value" (id SERIAL NOT NULL, "dimension_id" int4, "create_uid" int4, "write_uid" int4, "code" VARCHAR, "name" VARCHAR NOT NULL, "create_date" timestamp, "write_date" timestamp, PRIMARY KEY(id)); COMMENT ON TABLE "account_dimension_value" IS 'account.dimension.value'; COMMENT ON COLUMN "account_dimension_value"."dimension_id" IS 'Thuộc chiều phân tích'; COMMENT ON COLUMN "account_dimension_value"."create_uid" IS 'Created by'; COMMENT ON COLUMN "account_dimension_value"."write_uid" IS 'Last Updated by'; COMMENT ON COLUMN "account_dimension_value"."code" IS 'Mã'; COMMENT ON COLUMN "account_dimension_value"."name" IS 'Tên giá trị'; COMMENT ON COLUMN "account_dimension_value"."create_date" IS 'Created on'; COMMENT ON COLUMN "account_dimension_value"."write_date" IS 'Last Updated on';
ALTER TABLE "account_dimension" ALTER COLUMN "company_id" SET NOT NULL;
ALTER TABLE "dimension_account_rel" ADD FOREIGN KEY ("dimension_id") REFERENCES "account_dimension"("id") ON DELETE cascade;
ALTER TABLE "dimension_account_rel" ADD FOREIGN KEY ("account_id") REFERENCES "account_account"("id") ON DELETE cascade;
ALTER TABLE "account_dimension" ADD FOREIGN KEY ("company_id") REFERENCES "res_company"("id") ON DELETE restrict;
ALTER TABLE "account_dimension_value" ADD FOREIGN KEY ("dimension_id") REFERENCES "account_dimension"("id") ON DELETE cascade;
ALTER TABLE "account_dimension_value" ADD FOREIGN KEY ("create_uid") REFERENCES "res_users"("id") ON DELETE set null;
ALTER TABLE "account_dimension_value" ADD FOREIGN KEY ("write_uid") REFERENCES "res_users"("id") ON DELETE set null;

-- --- AUDIT LOG: 2026-03-25 02:39:44 ---
CREATE TABLE "dimension_account_rel" ("dimension_id" INTEGER NOT NULL,
                                          "account_id" INTEGER NOT NULL,
                                          PRIMARY KEY("dimension_id", "account_id"));
                    COMMENT ON TABLE "dimension_account_rel" IS 'RELATION BETWEEN account_dimension AND account_account';
                    CREATE INDEX ON "dimension_account_rel" ("account_id", "dimension_id");
ALTER TABLE "account_dimension" ADD COLUMN "company_id" int4 ; COMMENT ON COLUMN "account_dimension"."company_id" IS 'Công ty áp dụng';
ALTER TABLE "account_dimension" ALTER COLUMN "code" DROP NOT NULL;
CREATE TABLE "account_dimension_value" (id SERIAL NOT NULL, "dimension_id" int4, "create_uid" int4, "write_uid" int4, "code" VARCHAR, "name" VARCHAR NOT NULL, "create_date" timestamp, "write_date" timestamp, PRIMARY KEY(id)); COMMENT ON TABLE "account_dimension_value" IS 'account.dimension.value'; COMMENT ON COLUMN "account_dimension_value"."dimension_id" IS 'Thuộc chiều phân tích'; COMMENT ON COLUMN "account_dimension_value"."create_uid" IS 'Created by'; COMMENT ON COLUMN "account_dimension_value"."write_uid" IS 'Last Updated by'; COMMENT ON COLUMN "account_dimension_value"."code" IS 'Mã'; COMMENT ON COLUMN "account_dimension_value"."name" IS 'Tên giá trị'; COMMENT ON COLUMN "account_dimension_value"."create_date" IS 'Created on'; COMMENT ON COLUMN "account_dimension_value"."write_date" IS 'Last Updated on';
ALTER TABLE "account_dimension" ALTER COLUMN "company_id" SET NOT NULL;
ALTER TABLE "dimension_account_rel" ADD FOREIGN KEY ("dimension_id") REFERENCES "account_dimension"("id") ON DELETE cascade;
ALTER TABLE "dimension_account_rel" ADD FOREIGN KEY ("account_id") REFERENCES "account_account"("id") ON DELETE cascade;
ALTER TABLE "account_dimension" ADD FOREIGN KEY ("company_id") REFERENCES "res_company"("id") ON DELETE restrict;
ALTER TABLE "account_dimension_value" ADD FOREIGN KEY ("dimension_id") REFERENCES "account_dimension"("id") ON DELETE cascade;
ALTER TABLE "account_dimension_value" ADD FOREIGN KEY ("create_uid") REFERENCES "res_users"("id") ON DELETE set null;
ALTER TABLE "account_dimension_value" ADD FOREIGN KEY ("write_uid") REFERENCES "res_users"("id") ON DELETE set null;

-- --- AUDIT LOG: 2026-03-25 04:13:50 ---
CREATE TABLE "account_dimension" (id SERIAL NOT NULL, "company_id" int4 NOT NULL, "create_uid" int4, "write_uid" int4, "name" VARCHAR NOT NULL, "code" VARCHAR, "create_date" timestamp, "write_date" timestamp, PRIMARY KEY(id)); COMMENT ON TABLE "account_dimension" IS 'account.dimension'; COMMENT ON COLUMN "account_dimension"."company_id" IS 'Công ty áp dụng'; COMMENT ON COLUMN "account_dimension"."create_uid" IS 'Created by'; COMMENT ON COLUMN "account_dimension"."write_uid" IS 'Last Updated by'; COMMENT ON COLUMN "account_dimension"."name" IS 'Tên chiều PT'; COMMENT ON COLUMN "account_dimension"."code" IS 'Mã chiều PT'; COMMENT ON COLUMN "account_dimension"."create_date" IS 'Created on'; COMMENT ON COLUMN "account_dimension"."write_date" IS 'Last Updated on';
CREATE TABLE "dimension_account_rel" ("dimension_id" INTEGER NOT NULL,
                                          "account_id" INTEGER NOT NULL,
                                          PRIMARY KEY("dimension_id", "account_id"));
                    COMMENT ON TABLE "dimension_account_rel" IS 'RELATION BETWEEN account_dimension AND account_account';
                    CREATE INDEX ON "dimension_account_rel" ("account_id", "dimension_id");
ALTER TABLE "account_dimension" ADD CONSTRAINT "account_dimension_check_code_uniq" unique(code);
COMMENT ON CONSTRAINT "account_dimension_check_code_uniq" ON "account_dimension" IS 'unique(code)';
CREATE TABLE "account_dimension_value" (id SERIAL NOT NULL, "dimension_id" int4, "create_uid" int4, "write_uid" int4, "code" VARCHAR, "name" VARCHAR NOT NULL, "create_date" timestamp, "write_date" timestamp, PRIMARY KEY(id)); COMMENT ON TABLE "account_dimension_value" IS 'account.dimension.value'; COMMENT ON COLUMN "account_dimension_value"."dimension_id" IS 'Thuộc chiều phân tích'; COMMENT ON COLUMN "account_dimension_value"."create_uid" IS 'Created by'; COMMENT ON COLUMN "account_dimension_value"."write_uid" IS 'Last Updated by'; COMMENT ON COLUMN "account_dimension_value"."code" IS 'Mã'; COMMENT ON COLUMN "account_dimension_value"."name" IS 'Tên giá trị'; COMMENT ON COLUMN "account_dimension_value"."create_date" IS 'Created on'; COMMENT ON COLUMN "account_dimension_value"."write_date" IS 'Last Updated on';
CREATE TABLE "business_segment" (id SERIAL NOT NULL, "create_uid" int4, "write_uid" int4, "name" VARCHAR NOT NULL, "code" VARCHAR NOT NULL, "create_date" timestamp, "write_date" timestamp, PRIMARY KEY(id)); COMMENT ON TABLE "business_segment" IS 'Mảng kinh doanh'; COMMENT ON COLUMN "business_segment"."create_uid" IS 'Created by'; COMMENT ON COLUMN "business_segment"."write_uid" IS 'Last Updated by'; COMMENT ON COLUMN "business_segment"."name" IS 'Tên mảng KD'; COMMENT ON COLUMN "business_segment"."code" IS 'Mã mảng KD'; COMMENT ON COLUMN "business_segment"."create_date" IS 'Created on'; COMMENT ON COLUMN "business_segment"."write_date" IS 'Last Updated on';
ALTER TABLE "business_segment" ADD CONSTRAINT "business_segment_check_code_uniq" unique(code);
COMMENT ON CONSTRAINT "business_segment_check_code_uniq" ON "business_segment" IS 'unique(code)';
ALTER TABLE "dimension_account_rel" ADD FOREIGN KEY ("dimension_id") REFERENCES "account_dimension"("id") ON DELETE cascade;
ALTER TABLE "dimension_account_rel" ADD FOREIGN KEY ("account_id") REFERENCES "account_account"("id") ON DELETE cascade;
ALTER TABLE "account_dimension" ADD FOREIGN KEY ("company_id") REFERENCES "res_company"("id") ON DELETE restrict;
ALTER TABLE "account_dimension" ADD FOREIGN KEY ("create_uid") REFERENCES "res_users"("id") ON DELETE set null;
ALTER TABLE "account_dimension" ADD FOREIGN KEY ("write_uid") REFERENCES "res_users"("id") ON DELETE set null;
ALTER TABLE "account_dimension_value" ADD FOREIGN KEY ("dimension_id") REFERENCES "account_dimension"("id") ON DELETE cascade;
ALTER TABLE "account_dimension_value" ADD FOREIGN KEY ("create_uid") REFERENCES "res_users"("id") ON DELETE set null;
ALTER TABLE "account_dimension_value" ADD FOREIGN KEY ("write_uid") REFERENCES "res_users"("id") ON DELETE set null;
ALTER TABLE "business_segment" ADD FOREIGN KEY ("create_uid") REFERENCES "res_users"("id") ON DELETE set null;
ALTER TABLE "business_segment" ADD FOREIGN KEY ("write_uid") REFERENCES "res_users"("id") ON DELETE set null;

-- --- AUDIT LOG: 2026-03-25 10:22:09 ---
CREATE TABLE "account_financial_summary" (id SERIAL NOT NULL, "business_segment_id" int4, "partner_id" int4, "cost_center_id" int4, "dimension_id" int4, "account_id" int4, "currency_id" int4, "company_id" int4, "create_uid" int4, "write_uid" int4, "data_type" VARCHAR, "item_name" VARCHAR, "sub_item_name" VARCHAR, "content" VARCHAR, "in_system" VARCHAR, "date" date, "note" text, "amount" numeric, "create_date" timestamp, "write_date" timestamp, PRIMARY KEY(id)); COMMENT ON TABLE "account_financial_summary" IS 'Tổng hợp dữ liệu tài chính'; COMMENT ON COLUMN "account_financial_summary"."business_segment_id" IS 'Mảng kinh doanh'; COMMENT ON COLUMN "account_financial_summary"."partner_id" IS 'Pháp nhân'; COMMENT ON COLUMN "account_financial_summary"."cost_center_id" IS 'Cost center'; COMMENT ON COLUMN "account_financial_summary"."dimension_id" IS 'Chiều phân tích'; COMMENT ON COLUMN "account_financial_summary"."account_id" IS 'Tài khoản hạch toán'; COMMENT ON COLUMN "account_financial_summary"."currency_id" IS 'Nguyên tệ'; COMMENT ON COLUMN "account_financial_summary"."company_id" IS 'Công ty'; COMMENT ON COLUMN "account_financial_summary"."create_uid" IS 'Created by'; COMMENT ON COLUMN "account_financial_summary"."write_uid" IS 'Last Updated by'; COMMENT ON COLUMN "account_financial_summary"."data_type" IS 'Loại'; COMMENT ON COLUMN "account_financial_summary"."item_name" IS 'Khoản mục'; COMMENT ON COLUMN "account_financial_summary"."sub_item_name" IS 'Tiểu mục'; COMMENT ON COLUMN "account_financial_summary"."content" IS 'Nội dung'; COMMENT ON COLUMN "account_financial_summary"."in_system" IS 'Có hay không trên hệ thống'; COMMENT ON COLUMN "account_financial_summary"."date" IS 'Ngày'; COMMENT ON COLUMN "account_financial_summary"."note" IS 'Ghi chú'; COMMENT ON COLUMN "account_financial_summary"."amount" IS 'Số tiền'; COMMENT ON COLUMN "account_financial_summary"."create_date" IS 'Created on'; COMMENT ON COLUMN "account_financial_summary"."write_date" IS 'Last Updated on';
ALTER TABLE "account_financial_summary" ADD FOREIGN KEY ("business_segment_id") REFERENCES "business_segment"("id") ON DELETE set null;
ALTER TABLE "account_financial_summary" ADD FOREIGN KEY ("partner_id") REFERENCES "res_partner"("id") ON DELETE set null;
ALTER TABLE "account_financial_summary" ADD FOREIGN KEY ("cost_center_id") REFERENCES "account_analytic_account"("id") ON DELETE set null;
ALTER TABLE "account_financial_summary" ADD FOREIGN KEY ("dimension_id") REFERENCES "account_dimension"("id") ON DELETE set null;
ALTER TABLE "account_financial_summary" ADD FOREIGN KEY ("account_id") REFERENCES "account_account"("id") ON DELETE set null;
ALTER TABLE "account_financial_summary" ADD FOREIGN KEY ("currency_id") REFERENCES "res_currency"("id") ON DELETE set null;
ALTER TABLE "account_financial_summary" ADD FOREIGN KEY ("company_id") REFERENCES "res_company"("id") ON DELETE set null;
ALTER TABLE "account_financial_summary" ADD FOREIGN KEY ("create_uid") REFERENCES "res_users"("id") ON DELETE set null;
ALTER TABLE "account_financial_summary" ADD FOREIGN KEY ("write_uid") REFERENCES "res_users"("id") ON DELETE set null;

-- --- AUDIT LOG: 2026-03-25 10:24:03 ---
CREATE TABLE "account_financial_summary" (id SERIAL NOT NULL, "business_segment_id" int4, "partner_id" int4, "cost_center_id" int4, "dimension_id" int4, "account_id" int4, "currency_id" int4, "company_id" int4, "create_uid" int4, "write_uid" int4, "data_type" VARCHAR, "item_name" VARCHAR, "sub_item_name" VARCHAR, "content" VARCHAR, "in_system" VARCHAR, "date" date, "note" text, "amount" numeric, "create_date" timestamp, "write_date" timestamp, PRIMARY KEY(id)); COMMENT ON TABLE "account_financial_summary" IS 'Tổng hợp dữ liệu tài chính'; COMMENT ON COLUMN "account_financial_summary"."business_segment_id" IS 'Mảng kinh doanh'; COMMENT ON COLUMN "account_financial_summary"."partner_id" IS 'Pháp nhân'; COMMENT ON COLUMN "account_financial_summary"."cost_center_id" IS 'Cost center'; COMMENT ON COLUMN "account_financial_summary"."dimension_id" IS 'Chiều phân tích'; COMMENT ON COLUMN "account_financial_summary"."account_id" IS 'Tài khoản hạch toán'; COMMENT ON COLUMN "account_financial_summary"."currency_id" IS 'Nguyên tệ'; COMMENT ON COLUMN "account_financial_summary"."company_id" IS 'Công ty'; COMMENT ON COLUMN "account_financial_summary"."create_uid" IS 'Created by'; COMMENT ON COLUMN "account_financial_summary"."write_uid" IS 'Last Updated by'; COMMENT ON COLUMN "account_financial_summary"."data_type" IS 'Loại'; COMMENT ON COLUMN "account_financial_summary"."item_name" IS 'Khoản mục'; COMMENT ON COLUMN "account_financial_summary"."sub_item_name" IS 'Tiểu mục'; COMMENT ON COLUMN "account_financial_summary"."content" IS 'Nội dung'; COMMENT ON COLUMN "account_financial_summary"."in_system" IS 'Có hay không trên hệ thống'; COMMENT ON COLUMN "account_financial_summary"."date" IS 'Ngày'; COMMENT ON COLUMN "account_financial_summary"."note" IS 'Ghi chú'; COMMENT ON COLUMN "account_financial_summary"."amount" IS 'Số tiền'; COMMENT ON COLUMN "account_financial_summary"."create_date" IS 'Created on'; COMMENT ON COLUMN "account_financial_summary"."write_date" IS 'Last Updated on';
ALTER TABLE "account_financial_summary" ADD FOREIGN KEY ("business_segment_id") REFERENCES "business_segment"("id") ON DELETE set null;
ALTER TABLE "account_financial_summary" ADD FOREIGN KEY ("partner_id") REFERENCES "res_partner"("id") ON DELETE set null;
ALTER TABLE "account_financial_summary" ADD FOREIGN KEY ("cost_center_id") REFERENCES "account_analytic_account"("id") ON DELETE set null;
ALTER TABLE "account_financial_summary" ADD FOREIGN KEY ("dimension_id") REFERENCES "account_dimension"("id") ON DELETE set null;
ALTER TABLE "account_financial_summary" ADD FOREIGN KEY ("account_id") REFERENCES "account_account"("id") ON DELETE set null;
ALTER TABLE "account_financial_summary" ADD FOREIGN KEY ("currency_id") REFERENCES "res_currency"("id") ON DELETE set null;
ALTER TABLE "account_financial_summary" ADD FOREIGN KEY ("company_id") REFERENCES "res_company"("id") ON DELETE set null;
ALTER TABLE "account_financial_summary" ADD FOREIGN KEY ("create_uid") REFERENCES "res_users"("id") ON DELETE set null;
ALTER TABLE "account_financial_summary" ADD FOREIGN KEY ("write_uid") REFERENCES "res_users"("id") ON DELETE set null;

-- --- AUDIT LOG: 2026-03-25 11:43:26 ---
ALTER TABLE "account_financial_summary" ADD COLUMN "offset_account_id" int4 ; COMMENT ON COLUMN "account_financial_summary"."offset_account_id" IS 'Tài khoản đối ứng';
ALTER TABLE "account_financial_summary" ADD COLUMN "accounting_item" VARCHAR ; COMMENT ON COLUMN "account_financial_summary"."accounting_item" IS 'Khoản mục';
ALTER TABLE "account_financial_summary" ADD COLUMN "sub_accounting_item" VARCHAR ; COMMENT ON COLUMN "account_financial_summary"."sub_accounting_item" IS 'Tiểu mục';
ALTER TABLE "account_financial_summary" ADD FOREIGN KEY ("offset_account_id") REFERENCES "account_account"("id") ON DELETE set null;

-- --- AUDIT LOG: 2026-03-26 01:21:17 ---
ALTER TABLE "account_financial_summary" ALTER COLUMN "partner_id" DROP NOT NULL;
ALTER TABLE "account_financial_summary" ALTER COLUMN "cost_center_id" DROP NOT NULL;
ALTER TABLE "account_financial_summary" ADD COLUMN "offset_account_id" int4 ; COMMENT ON COLUMN "account_financial_summary"."offset_account_id" IS 'Tài khoản đối ứng';
ALTER TABLE "account_financial_summary" ALTER COLUMN "currency_id" DROP NOT NULL;
ALTER TABLE "account_financial_summary" ALTER COLUMN "company_id" DROP NOT NULL;
ALTER TABLE "account_financial_summary" ALTER COLUMN "data_type" DROP NOT NULL;
ALTER TABLE "account_financial_summary" ADD COLUMN "accounting_item" VARCHAR ; COMMENT ON COLUMN "account_financial_summary"."accounting_item" IS 'Khoản mục';
ALTER TABLE "account_financial_summary" ADD COLUMN "sub_accounting_item" VARCHAR ; COMMENT ON COLUMN "account_financial_summary"."sub_accounting_item" IS 'Tiểu mục';
ALTER TABLE "account_financial_summary" ALTER COLUMN "date" DROP NOT NULL;
ALTER TABLE "account_financial_summary" DROP CONSTRAINT "account_financial_summary_partner_id_fkey";
ALTER TABLE "account_financial_summary" ADD FOREIGN KEY ("partner_id") REFERENCES "res_partner"("id") ON DELETE set null;
ALTER TABLE "account_financial_summary" DROP CONSTRAINT "account_financial_summary_cost_center_id_fkey";
ALTER TABLE "account_financial_summary" ADD FOREIGN KEY ("cost_center_id") REFERENCES "account_analytic_account"("id") ON DELETE set null;
ALTER TABLE "account_financial_summary" ADD FOREIGN KEY ("offset_account_id") REFERENCES "account_account"("id") ON DELETE set null;
ALTER TABLE "account_financial_summary" DROP CONSTRAINT "account_financial_summary_currency_id_fkey";
ALTER TABLE "account_financial_summary" ADD FOREIGN KEY ("currency_id") REFERENCES "res_currency"("id") ON DELETE set null;
ALTER TABLE "account_financial_summary" DROP CONSTRAINT "account_financial_summary_company_id_fkey";
ALTER TABLE "account_financial_summary" ADD FOREIGN KEY ("company_id") REFERENCES "res_company"("id") ON DELETE set null;

-- --- AUDIT LOG: 2026-03-26 01:54:40 ---
CREATE TABLE "account_dimension" (id SERIAL NOT NULL, "company_id" int4 NOT NULL, "create_uid" int4, "write_uid" int4, "name" VARCHAR NOT NULL, "code" VARCHAR, "create_date" timestamp, "write_date" timestamp, PRIMARY KEY(id)); COMMENT ON TABLE "account_dimension" IS 'account.dimension'; COMMENT ON COLUMN "account_dimension"."company_id" IS 'Công ty áp dụng'; COMMENT ON COLUMN "account_dimension"."create_uid" IS 'Created by'; COMMENT ON COLUMN "account_dimension"."write_uid" IS 'Last Updated by'; COMMENT ON COLUMN "account_dimension"."name" IS 'Tên chiều PT'; COMMENT ON COLUMN "account_dimension"."code" IS 'Mã chiều PT'; COMMENT ON COLUMN "account_dimension"."create_date" IS 'Created on'; COMMENT ON COLUMN "account_dimension"."write_date" IS 'Last Updated on';
CREATE TABLE "dimension_account_rel" ("dimension_id" INTEGER NOT NULL,
                                          "account_id" INTEGER NOT NULL,
                                          PRIMARY KEY("dimension_id", "account_id"));
                    COMMENT ON TABLE "dimension_account_rel" IS 'RELATION BETWEEN account_dimension AND account_account';
                    CREATE INDEX ON "dimension_account_rel" ("account_id", "dimension_id");
ALTER TABLE "account_dimension" ADD CONSTRAINT "account_dimension_check_code_uniq" unique(code);
COMMENT ON CONSTRAINT "account_dimension_check_code_uniq" ON "account_dimension" IS 'unique(code)';
CREATE TABLE "account_dimension_value" (id SERIAL NOT NULL, "dimension_id" int4, "create_uid" int4, "write_uid" int4, "code" VARCHAR, "name" VARCHAR NOT NULL, "create_date" timestamp, "write_date" timestamp, PRIMARY KEY(id)); COMMENT ON TABLE "account_dimension_value" IS 'account.dimension.value'; COMMENT ON COLUMN "account_dimension_value"."dimension_id" IS 'Thuộc chiều phân tích'; COMMENT ON COLUMN "account_dimension_value"."create_uid" IS 'Created by'; COMMENT ON COLUMN "account_dimension_value"."write_uid" IS 'Last Updated by'; COMMENT ON COLUMN "account_dimension_value"."code" IS 'Mã'; COMMENT ON COLUMN "account_dimension_value"."name" IS 'Tên giá trị'; COMMENT ON COLUMN "account_dimension_value"."create_date" IS 'Created on'; COMMENT ON COLUMN "account_dimension_value"."write_date" IS 'Last Updated on';
CREATE TABLE "business_segment" (id SERIAL NOT NULL, "create_uid" int4, "write_uid" int4, "name" VARCHAR NOT NULL, "code" VARCHAR NOT NULL, "create_date" timestamp, "write_date" timestamp, PRIMARY KEY(id)); COMMENT ON TABLE "business_segment" IS 'Mảng kinh doanh'; COMMENT ON COLUMN "business_segment"."create_uid" IS 'Created by'; COMMENT ON COLUMN "business_segment"."write_uid" IS 'Last Updated by'; COMMENT ON COLUMN "business_segment"."name" IS 'Tên mảng KD'; COMMENT ON COLUMN "business_segment"."code" IS 'Mã mảng KD'; COMMENT ON COLUMN "business_segment"."create_date" IS 'Created on'; COMMENT ON COLUMN "business_segment"."write_date" IS 'Last Updated on';
ALTER TABLE "business_segment" ADD CONSTRAINT "business_segment_check_code_uniq" unique(code);
COMMENT ON CONSTRAINT "business_segment_check_code_uniq" ON "business_segment" IS 'unique(code)';
CREATE TABLE "account_financial_summary" (id SERIAL NOT NULL, "business_segment_id" int4, "partner_id" int4, "cost_center_id" int4, "dimension_id" int4, "account_id" int4, "offset_account_id" int4, "currency_id" int4, "company_id" int4, "create_uid" int4, "write_uid" int4, "data_type" VARCHAR, "accounting_item" VARCHAR, "sub_accounting_item" VARCHAR, "content" VARCHAR, "in_system" VARCHAR, "date" date, "note" text, "amount" numeric, "create_date" timestamp, "write_date" timestamp, PRIMARY KEY(id)); COMMENT ON TABLE "account_financial_summary" IS 'Tổng hợp dữ liệu tài chính'; COMMENT ON COLUMN "account_financial_summary"."business_segment_id" IS 'Mảng kinh doanh'; COMMENT ON COLUMN "account_financial_summary"."partner_id" IS 'Pháp nhân'; COMMENT ON COLUMN "account_financial_summary"."cost_center_id" IS 'Cost center'; COMMENT ON COLUMN "account_financial_summary"."dimension_id" IS 'Chiều phân tích'; COMMENT ON COLUMN "account_financial_summary"."account_id" IS 'Tài khoản hạch toán'; COMMENT ON COLUMN "account_financial_summary"."offset_account_id" IS 'Tài khoản đối ứng'; COMMENT ON COLUMN "account_financial_summary"."currency_id" IS 'Nguyên tệ'; COMMENT ON COLUMN "account_financial_summary"."company_id" IS 'Công ty'; COMMENT ON COLUMN "account_financial_summary"."create_uid" IS 'Created by'; COMMENT ON COLUMN "account_financial_summary"."write_uid" IS 'Last Updated by'; COMMENT ON COLUMN "account_financial_summary"."data_type" IS 'Loại'; COMMENT ON COLUMN "account_financial_summary"."accounting_item" IS 'Khoản mục'; COMMENT ON COLUMN "account_financial_summary"."sub_accounting_item" IS 'Tiểu mục'; COMMENT ON COLUMN "account_financial_summary"."content" IS 'Nội dung'; COMMENT ON COLUMN "account_financial_summary"."in_system" IS 'Có hay không trên hệ thống'; COMMENT ON COLUMN "account_financial_summary"."date" IS 'Ngày'; COMMENT ON COLUMN "account_financial_summary"."note" IS 'Ghi chú'; COMMENT ON COLUMN "account_financial_summary"."amount" IS 'Số tiền'; COMMENT ON COLUMN "account_financial_summary"."create_date" IS 'Created on'; COMMENT ON COLUMN "account_financial_summary"."write_date" IS 'Last Updated on';
ALTER TABLE "dimension_account_rel" ADD FOREIGN KEY ("dimension_id") REFERENCES "account_dimension"("id") ON DELETE cascade;
ALTER TABLE "dimension_account_rel" ADD FOREIGN KEY ("account_id") REFERENCES "account_account"("id") ON DELETE cascade;
ALTER TABLE "account_dimension" ADD FOREIGN KEY ("company_id") REFERENCES "res_company"("id") ON DELETE restrict;
ALTER TABLE "account_dimension" ADD FOREIGN KEY ("create_uid") REFERENCES "res_users"("id") ON DELETE set null;
ALTER TABLE "account_dimension" ADD FOREIGN KEY ("write_uid") REFERENCES "res_users"("id") ON DELETE set null;
ALTER TABLE "account_dimension_value" ADD FOREIGN KEY ("dimension_id") REFERENCES "account_dimension"("id") ON DELETE cascade;
ALTER TABLE "account_dimension_value" ADD FOREIGN KEY ("create_uid") REFERENCES "res_users"("id") ON DELETE set null;
ALTER TABLE "account_dimension_value" ADD FOREIGN KEY ("write_uid") REFERENCES "res_users"("id") ON DELETE set null;
ALTER TABLE "business_segment" ADD FOREIGN KEY ("create_uid") REFERENCES "res_users"("id") ON DELETE set null;
ALTER TABLE "business_segment" ADD FOREIGN KEY ("write_uid") REFERENCES "res_users"("id") ON DELETE set null;
ALTER TABLE "account_financial_summary" ADD FOREIGN KEY ("business_segment_id") REFERENCES "business_segment"("id") ON DELETE set null;
ALTER TABLE "account_financial_summary" ADD FOREIGN KEY ("partner_id") REFERENCES "res_partner"("id") ON DELETE set null;
ALTER TABLE "account_financial_summary" ADD FOREIGN KEY ("cost_center_id") REFERENCES "account_analytic_account"("id") ON DELETE set null;
ALTER TABLE "account_financial_summary" ADD FOREIGN KEY ("dimension_id") REFERENCES "account_dimension"("id") ON DELETE set null;
ALTER TABLE "account_financial_summary" ADD FOREIGN KEY ("account_id") REFERENCES "account_account"("id") ON DELETE set null;
ALTER TABLE "account_financial_summary" ADD FOREIGN KEY ("offset_account_id") REFERENCES "account_account"("id") ON DELETE set null;
ALTER TABLE "account_financial_summary" ADD FOREIGN KEY ("currency_id") REFERENCES "res_currency"("id") ON DELETE set null;
ALTER TABLE "account_financial_summary" ADD FOREIGN KEY ("company_id") REFERENCES "res_company"("id") ON DELETE set null;
ALTER TABLE "account_financial_summary" ADD FOREIGN KEY ("create_uid") REFERENCES "res_users"("id") ON DELETE set null;
ALTER TABLE "account_financial_summary" ADD FOREIGN KEY ("write_uid") REFERENCES "res_users"("id") ON DELETE set null;

-- --- AUDIT LOG: 2026-03-26 02:01:58 ---
CREATE TABLE "account_dimension" (id SERIAL NOT NULL, "company_id" int4 NOT NULL, "create_uid" int4, "write_uid" int4, "name" VARCHAR NOT NULL, "code" VARCHAR, "create_date" timestamp, "write_date" timestamp, PRIMARY KEY(id)); COMMENT ON TABLE "account_dimension" IS 'account.dimension'; COMMENT ON COLUMN "account_dimension"."company_id" IS 'Công ty áp dụng'; COMMENT ON COLUMN "account_dimension"."create_uid" IS 'Created by'; COMMENT ON COLUMN "account_dimension"."write_uid" IS 'Last Updated by'; COMMENT ON COLUMN "account_dimension"."name" IS 'Tên chiều PT'; COMMENT ON COLUMN "account_dimension"."code" IS 'Mã chiều PT'; COMMENT ON COLUMN "account_dimension"."create_date" IS 'Created on'; COMMENT ON COLUMN "account_dimension"."write_date" IS 'Last Updated on';
CREATE TABLE "dimension_account_rel" ("dimension_id" INTEGER NOT NULL,
                                          "account_id" INTEGER NOT NULL,
                                          PRIMARY KEY("dimension_id", "account_id"));
                    COMMENT ON TABLE "dimension_account_rel" IS 'RELATION BETWEEN account_dimension AND account_account';
                    CREATE INDEX ON "dimension_account_rel" ("account_id", "dimension_id");
ALTER TABLE "account_dimension" ADD CONSTRAINT "account_dimension_check_code_uniq" unique(code);
COMMENT ON CONSTRAINT "account_dimension_check_code_uniq" ON "account_dimension" IS 'unique(code)';
CREATE TABLE "account_dimension_value" (id SERIAL NOT NULL, "dimension_id" int4, "create_uid" int4, "write_uid" int4, "code" VARCHAR, "name" VARCHAR NOT NULL, "create_date" timestamp, "write_date" timestamp, PRIMARY KEY(id)); COMMENT ON TABLE "account_dimension_value" IS 'account.dimension.value'; COMMENT ON COLUMN "account_dimension_value"."dimension_id" IS 'Thuộc chiều phân tích'; COMMENT ON COLUMN "account_dimension_value"."create_uid" IS 'Created by'; COMMENT ON COLUMN "account_dimension_value"."write_uid" IS 'Last Updated by'; COMMENT ON COLUMN "account_dimension_value"."code" IS 'Mã'; COMMENT ON COLUMN "account_dimension_value"."name" IS 'Tên giá trị'; COMMENT ON COLUMN "account_dimension_value"."create_date" IS 'Created on'; COMMENT ON COLUMN "account_dimension_value"."write_date" IS 'Last Updated on';
CREATE TABLE "business_segment" (id SERIAL NOT NULL, "create_uid" int4, "write_uid" int4, "name" VARCHAR NOT NULL, "code" VARCHAR NOT NULL, "create_date" timestamp, "write_date" timestamp, PRIMARY KEY(id)); COMMENT ON TABLE "business_segment" IS 'Mảng kinh doanh'; COMMENT ON COLUMN "business_segment"."create_uid" IS 'Created by'; COMMENT ON COLUMN "business_segment"."write_uid" IS 'Last Updated by'; COMMENT ON COLUMN "business_segment"."name" IS 'Tên mảng KD'; COMMENT ON COLUMN "business_segment"."code" IS 'Mã mảng KD'; COMMENT ON COLUMN "business_segment"."create_date" IS 'Created on'; COMMENT ON COLUMN "business_segment"."write_date" IS 'Last Updated on';
ALTER TABLE "business_segment" ADD CONSTRAINT "business_segment_check_code_uniq" unique(code);
COMMENT ON CONSTRAINT "business_segment_check_code_uniq" ON "business_segment" IS 'unique(code)';
CREATE TABLE "account_financial_summary" (id SERIAL NOT NULL, "business_segment_id" int4, "partner_id" int4, "cost_center_id" int4, "dimension_id" int4, "account_id" int4, "offset_account_id" int4, "currency_id" int4, "company_id" int4, "create_uid" int4, "write_uid" int4, "data_type" VARCHAR, "accounting_item" VARCHAR, "sub_accounting_item" VARCHAR, "content" VARCHAR, "in_system" VARCHAR, "date" date, "note" text, "amount" numeric, "create_date" timestamp, "write_date" timestamp, PRIMARY KEY(id)); COMMENT ON TABLE "account_financial_summary" IS 'Tổng hợp dữ liệu tài chính'; COMMENT ON COLUMN "account_financial_summary"."business_segment_id" IS 'Mảng kinh doanh'; COMMENT ON COLUMN "account_financial_summary"."partner_id" IS 'Pháp nhân'; COMMENT ON COLUMN "account_financial_summary"."cost_center_id" IS 'Cost center'; COMMENT ON COLUMN "account_financial_summary"."dimension_id" IS 'Chiều phân tích'; COMMENT ON COLUMN "account_financial_summary"."account_id" IS 'Tài khoản hạch toán'; COMMENT ON COLUMN "account_financial_summary"."offset_account_id" IS 'Tài khoản đối ứng'; COMMENT ON COLUMN "account_financial_summary"."currency_id" IS 'Nguyên tệ'; COMMENT ON COLUMN "account_financial_summary"."company_id" IS 'Công ty'; COMMENT ON COLUMN "account_financial_summary"."create_uid" IS 'Created by'; COMMENT ON COLUMN "account_financial_summary"."write_uid" IS 'Last Updated by'; COMMENT ON COLUMN "account_financial_summary"."data_type" IS 'Loại'; COMMENT ON COLUMN "account_financial_summary"."accounting_item" IS 'Khoản mục'; COMMENT ON COLUMN "account_financial_summary"."sub_accounting_item" IS 'Tiểu mục'; COMMENT ON COLUMN "account_financial_summary"."content" IS 'Nội dung'; COMMENT ON COLUMN "account_financial_summary"."in_system" IS 'Có hay không trên hệ thống'; COMMENT ON COLUMN "account_financial_summary"."date" IS 'Ngày'; COMMENT ON COLUMN "account_financial_summary"."note" IS 'Ghi chú'; COMMENT ON COLUMN "account_financial_summary"."amount" IS 'Số tiền'; COMMENT ON COLUMN "account_financial_summary"."create_date" IS 'Created on'; COMMENT ON COLUMN "account_financial_summary"."write_date" IS 'Last Updated on';
ALTER TABLE "dimension_account_rel" ADD FOREIGN KEY ("dimension_id") REFERENCES "account_dimension"("id") ON DELETE cascade;
ALTER TABLE "dimension_account_rel" ADD FOREIGN KEY ("account_id") REFERENCES "account_account"("id") ON DELETE cascade;
ALTER TABLE "account_dimension" ADD FOREIGN KEY ("company_id") REFERENCES "res_company"("id") ON DELETE restrict;
ALTER TABLE "account_dimension" ADD FOREIGN KEY ("create_uid") REFERENCES "res_users"("id") ON DELETE set null;
ALTER TABLE "account_dimension" ADD FOREIGN KEY ("write_uid") REFERENCES "res_users"("id") ON DELETE set null;
ALTER TABLE "account_dimension_value" ADD FOREIGN KEY ("dimension_id") REFERENCES "account_dimension"("id") ON DELETE cascade;
ALTER TABLE "account_dimension_value" ADD FOREIGN KEY ("create_uid") REFERENCES "res_users"("id") ON DELETE set null;
ALTER TABLE "account_dimension_value" ADD FOREIGN KEY ("write_uid") REFERENCES "res_users"("id") ON DELETE set null;
ALTER TABLE "business_segment" ADD FOREIGN KEY ("create_uid") REFERENCES "res_users"("id") ON DELETE set null;
ALTER TABLE "business_segment" ADD FOREIGN KEY ("write_uid") REFERENCES "res_users"("id") ON DELETE set null;
ALTER TABLE "account_financial_summary" ADD FOREIGN KEY ("business_segment_id") REFERENCES "business_segment"("id") ON DELETE set null;
ALTER TABLE "account_financial_summary" ADD FOREIGN KEY ("partner_id") REFERENCES "res_partner"("id") ON DELETE set null;
ALTER TABLE "account_financial_summary" ADD FOREIGN KEY ("cost_center_id") REFERENCES "account_analytic_account"("id") ON DELETE set null;
ALTER TABLE "account_financial_summary" ADD FOREIGN KEY ("dimension_id") REFERENCES "account_dimension"("id") ON DELETE set null;
ALTER TABLE "account_financial_summary" ADD FOREIGN KEY ("account_id") REFERENCES "account_account"("id") ON DELETE set null;
ALTER TABLE "account_financial_summary" ADD FOREIGN KEY ("offset_account_id") REFERENCES "account_account"("id") ON DELETE set null;
ALTER TABLE "account_financial_summary" ADD FOREIGN KEY ("currency_id") REFERENCES "res_currency"("id") ON DELETE set null;
ALTER TABLE "account_financial_summary" ADD FOREIGN KEY ("company_id") REFERENCES "res_company"("id") ON DELETE set null;
ALTER TABLE "account_financial_summary" ADD FOREIGN KEY ("create_uid") REFERENCES "res_users"("id") ON DELETE set null;
ALTER TABLE "account_financial_summary" ADD FOREIGN KEY ("write_uid") REFERENCES "res_users"("id") ON DELETE set null;

-- --- AUDIT LOG: 2026-03-26 02:07:28 ---
CREATE TABLE "account_dimension" (id SERIAL NOT NULL, "company_id" int4 NOT NULL, "create_uid" int4, "write_uid" int4, "name" VARCHAR NOT NULL, "code" VARCHAR, "create_date" timestamp, "write_date" timestamp, PRIMARY KEY(id)); COMMENT ON TABLE "account_dimension" IS 'account.dimension'; COMMENT ON COLUMN "account_dimension"."company_id" IS 'Công ty áp dụng'; COMMENT ON COLUMN "account_dimension"."create_uid" IS 'Created by'; COMMENT ON COLUMN "account_dimension"."write_uid" IS 'Last Updated by'; COMMENT ON COLUMN "account_dimension"."name" IS 'Tên chiều PT'; COMMENT ON COLUMN "account_dimension"."code" IS 'Mã chiều PT'; COMMENT ON COLUMN "account_dimension"."create_date" IS 'Created on'; COMMENT ON COLUMN "account_dimension"."write_date" IS 'Last Updated on';
CREATE TABLE "dimension_account_rel" ("dimension_id" INTEGER NOT NULL,
                                          "account_id" INTEGER NOT NULL,
                                          PRIMARY KEY("dimension_id", "account_id"));
                    COMMENT ON TABLE "dimension_account_rel" IS 'RELATION BETWEEN account_dimension AND account_account';
                    CREATE INDEX ON "dimension_account_rel" ("account_id", "dimension_id");
ALTER TABLE "account_dimension" ADD CONSTRAINT "account_dimension_check_code_uniq" unique(code);
COMMENT ON CONSTRAINT "account_dimension_check_code_uniq" ON "account_dimension" IS 'unique(code)';
CREATE TABLE "account_dimension_value" (id SERIAL NOT NULL, "dimension_id" int4, "create_uid" int4, "write_uid" int4, "code" VARCHAR, "name" VARCHAR NOT NULL, "create_date" timestamp, "write_date" timestamp, PRIMARY KEY(id)); COMMENT ON TABLE "account_dimension_value" IS 'account.dimension.value'; COMMENT ON COLUMN "account_dimension_value"."dimension_id" IS 'Thuộc chiều phân tích'; COMMENT ON COLUMN "account_dimension_value"."create_uid" IS 'Created by'; COMMENT ON COLUMN "account_dimension_value"."write_uid" IS 'Last Updated by'; COMMENT ON COLUMN "account_dimension_value"."code" IS 'Mã'; COMMENT ON COLUMN "account_dimension_value"."name" IS 'Tên giá trị'; COMMENT ON COLUMN "account_dimension_value"."create_date" IS 'Created on'; COMMENT ON COLUMN "account_dimension_value"."write_date" IS 'Last Updated on';
CREATE TABLE "business_segment" (id SERIAL NOT NULL, "create_uid" int4, "write_uid" int4, "name" VARCHAR NOT NULL, "code" VARCHAR NOT NULL, "create_date" timestamp, "write_date" timestamp, PRIMARY KEY(id)); COMMENT ON TABLE "business_segment" IS 'Mảng kinh doanh'; COMMENT ON COLUMN "business_segment"."create_uid" IS 'Created by'; COMMENT ON COLUMN "business_segment"."write_uid" IS 'Last Updated by'; COMMENT ON COLUMN "business_segment"."name" IS 'Tên mảng KD'; COMMENT ON COLUMN "business_segment"."code" IS 'Mã mảng KD'; COMMENT ON COLUMN "business_segment"."create_date" IS 'Created on'; COMMENT ON COLUMN "business_segment"."write_date" IS 'Last Updated on';
ALTER TABLE "business_segment" ADD CONSTRAINT "business_segment_check_code_uniq" unique(code);
COMMENT ON CONSTRAINT "business_segment_check_code_uniq" ON "business_segment" IS 'unique(code)';
CREATE TABLE "account_financial_summary" (id SERIAL NOT NULL, "business_segment_id" int4, "partner_id" int4, "cost_center_id" int4, "dimension_id" int4, "account_id" int4, "offset_account_id" int4, "currency_id" int4, "company_id" int4, "create_uid" int4, "write_uid" int4, "data_type" VARCHAR, "accounting_item" VARCHAR, "sub_accounting_item" VARCHAR, "content" VARCHAR, "in_system" VARCHAR, "date" date, "note" text, "amount" numeric, "create_date" timestamp, "write_date" timestamp, PRIMARY KEY(id)); COMMENT ON TABLE "account_financial_summary" IS 'Tổng hợp dữ liệu tài chính'; COMMENT ON COLUMN "account_financial_summary"."business_segment_id" IS 'Mảng kinh doanh'; COMMENT ON COLUMN "account_financial_summary"."partner_id" IS 'Pháp nhân'; COMMENT ON COLUMN "account_financial_summary"."cost_center_id" IS 'Cost center'; COMMENT ON COLUMN "account_financial_summary"."dimension_id" IS 'Chiều phân tích'; COMMENT ON COLUMN "account_financial_summary"."account_id" IS 'Tài khoản hạch toán'; COMMENT ON COLUMN "account_financial_summary"."offset_account_id" IS 'Tài khoản đối ứng'; COMMENT ON COLUMN "account_financial_summary"."currency_id" IS 'Nguyên tệ'; COMMENT ON COLUMN "account_financial_summary"."company_id" IS 'Công ty'; COMMENT ON COLUMN "account_financial_summary"."create_uid" IS 'Created by'; COMMENT ON COLUMN "account_financial_summary"."write_uid" IS 'Last Updated by'; COMMENT ON COLUMN "account_financial_summary"."data_type" IS 'Loại'; COMMENT ON COLUMN "account_financial_summary"."accounting_item" IS 'Khoản mục'; COMMENT ON COLUMN "account_financial_summary"."sub_accounting_item" IS 'Tiểu mục'; COMMENT ON COLUMN "account_financial_summary"."content" IS 'Nội dung'; COMMENT ON COLUMN "account_financial_summary"."in_system" IS 'Có hay không trên hệ thống'; COMMENT ON COLUMN "account_financial_summary"."date" IS 'Ngày'; COMMENT ON COLUMN "account_financial_summary"."note" IS 'Ghi chú'; COMMENT ON COLUMN "account_financial_summary"."amount" IS 'Số tiền'; COMMENT ON COLUMN "account_financial_summary"."create_date" IS 'Created on'; COMMENT ON COLUMN "account_financial_summary"."write_date" IS 'Last Updated on';
ALTER TABLE "dimension_account_rel" ADD FOREIGN KEY ("dimension_id") REFERENCES "account_dimension"("id") ON DELETE cascade;
ALTER TABLE "dimension_account_rel" ADD FOREIGN KEY ("account_id") REFERENCES "account_account"("id") ON DELETE cascade;
ALTER TABLE "account_dimension" ADD FOREIGN KEY ("company_id") REFERENCES "res_company"("id") ON DELETE restrict;
ALTER TABLE "account_dimension" ADD FOREIGN KEY ("create_uid") REFERENCES "res_users"("id") ON DELETE set null;
ALTER TABLE "account_dimension" ADD FOREIGN KEY ("write_uid") REFERENCES "res_users"("id") ON DELETE set null;
ALTER TABLE "account_dimension_value" ADD FOREIGN KEY ("dimension_id") REFERENCES "account_dimension"("id") ON DELETE cascade;
ALTER TABLE "account_dimension_value" ADD FOREIGN KEY ("create_uid") REFERENCES "res_users"("id") ON DELETE set null;
ALTER TABLE "account_dimension_value" ADD FOREIGN KEY ("write_uid") REFERENCES "res_users"("id") ON DELETE set null;
ALTER TABLE "business_segment" ADD FOREIGN KEY ("create_uid") REFERENCES "res_users"("id") ON DELETE set null;
ALTER TABLE "business_segment" ADD FOREIGN KEY ("write_uid") REFERENCES "res_users"("id") ON DELETE set null;
ALTER TABLE "account_financial_summary" ADD FOREIGN KEY ("business_segment_id") REFERENCES "business_segment"("id") ON DELETE set null;
ALTER TABLE "account_financial_summary" ADD FOREIGN KEY ("partner_id") REFERENCES "res_partner"("id") ON DELETE set null;
ALTER TABLE "account_financial_summary" ADD FOREIGN KEY ("cost_center_id") REFERENCES "account_analytic_account"("id") ON DELETE set null;
ALTER TABLE "account_financial_summary" ADD FOREIGN KEY ("dimension_id") REFERENCES "account_dimension"("id") ON DELETE set null;
ALTER TABLE "account_financial_summary" ADD FOREIGN KEY ("account_id") REFERENCES "account_account"("id") ON DELETE set null;
ALTER TABLE "account_financial_summary" ADD FOREIGN KEY ("offset_account_id") REFERENCES "account_account"("id") ON DELETE set null;
ALTER TABLE "account_financial_summary" ADD FOREIGN KEY ("currency_id") REFERENCES "res_currency"("id") ON DELETE set null;
ALTER TABLE "account_financial_summary" ADD FOREIGN KEY ("company_id") REFERENCES "res_company"("id") ON DELETE set null;
ALTER TABLE "account_financial_summary" ADD FOREIGN KEY ("create_uid") REFERENCES "res_users"("id") ON DELETE set null;
ALTER TABLE "account_financial_summary" ADD FOREIGN KEY ("write_uid") REFERENCES "res_users"("id") ON DELETE set null;

-- --- AUDIT LOG: 2026-03-26 02:12:52 ---
CREATE TABLE "account_dimension" (id SERIAL NOT NULL, "company_id" int4 NOT NULL, "create_uid" int4, "write_uid" int4, "name" VARCHAR NOT NULL, "code" VARCHAR, "create_date" timestamp, "write_date" timestamp, PRIMARY KEY(id)); COMMENT ON TABLE "account_dimension" IS 'account.dimension'; COMMENT ON COLUMN "account_dimension"."company_id" IS 'Công ty áp dụng'; COMMENT ON COLUMN "account_dimension"."create_uid" IS 'Created by'; COMMENT ON COLUMN "account_dimension"."write_uid" IS 'Last Updated by'; COMMENT ON COLUMN "account_dimension"."name" IS 'Tên chiều PT'; COMMENT ON COLUMN "account_dimension"."code" IS 'Mã chiều PT'; COMMENT ON COLUMN "account_dimension"."create_date" IS 'Created on'; COMMENT ON COLUMN "account_dimension"."write_date" IS 'Last Updated on';
CREATE TABLE "dimension_account_rel" ("dimension_id" INTEGER NOT NULL,
                                          "account_id" INTEGER NOT NULL,
                                          PRIMARY KEY("dimension_id", "account_id"));
                    COMMENT ON TABLE "dimension_account_rel" IS 'RELATION BETWEEN account_dimension AND account_account';
                    CREATE INDEX ON "dimension_account_rel" ("account_id", "dimension_id");
ALTER TABLE "account_dimension" ADD CONSTRAINT "account_dimension_check_code_uniq" unique(code);
COMMENT ON CONSTRAINT "account_dimension_check_code_uniq" ON "account_dimension" IS 'unique(code)';
CREATE TABLE "account_dimension_value" (id SERIAL NOT NULL, "dimension_id" int4, "create_uid" int4, "write_uid" int4, "code" VARCHAR, "name" VARCHAR NOT NULL, "create_date" timestamp, "write_date" timestamp, PRIMARY KEY(id)); COMMENT ON TABLE "account_dimension_value" IS 'account.dimension.value'; COMMENT ON COLUMN "account_dimension_value"."dimension_id" IS 'Thuộc chiều phân tích'; COMMENT ON COLUMN "account_dimension_value"."create_uid" IS 'Created by'; COMMENT ON COLUMN "account_dimension_value"."write_uid" IS 'Last Updated by'; COMMENT ON COLUMN "account_dimension_value"."code" IS 'Mã'; COMMENT ON COLUMN "account_dimension_value"."name" IS 'Tên giá trị'; COMMENT ON COLUMN "account_dimension_value"."create_date" IS 'Created on'; COMMENT ON COLUMN "account_dimension_value"."write_date" IS 'Last Updated on';
CREATE TABLE "business_segment" (id SERIAL NOT NULL, "create_uid" int4, "write_uid" int4, "name" VARCHAR NOT NULL, "code" VARCHAR NOT NULL, "create_date" timestamp, "write_date" timestamp, PRIMARY KEY(id)); COMMENT ON TABLE "business_segment" IS 'Mảng kinh doanh'; COMMENT ON COLUMN "business_segment"."create_uid" IS 'Created by'; COMMENT ON COLUMN "business_segment"."write_uid" IS 'Last Updated by'; COMMENT ON COLUMN "business_segment"."name" IS 'Tên mảng KD'; COMMENT ON COLUMN "business_segment"."code" IS 'Mã mảng KD'; COMMENT ON COLUMN "business_segment"."create_date" IS 'Created on'; COMMENT ON COLUMN "business_segment"."write_date" IS 'Last Updated on';
ALTER TABLE "business_segment" ADD CONSTRAINT "business_segment_check_code_uniq" unique(code);
COMMENT ON CONSTRAINT "business_segment_check_code_uniq" ON "business_segment" IS 'unique(code)';
CREATE TABLE "account_financial_summary" (id SERIAL NOT NULL, "business_segment_id" int4, "partner_id" int4, "cost_center_id" int4, "dimension_id" int4, "account_id" int4, "offset_account_id" int4, "currency_id" int4, "company_id" int4, "create_uid" int4, "write_uid" int4, "data_type" VARCHAR, "accounting_item" VARCHAR, "sub_accounting_item" VARCHAR, "content" VARCHAR, "in_system" VARCHAR, "date" date, "note" text, "amount" numeric, "create_date" timestamp, "write_date" timestamp, PRIMARY KEY(id)); COMMENT ON TABLE "account_financial_summary" IS 'Tổng hợp dữ liệu tài chính'; COMMENT ON COLUMN "account_financial_summary"."business_segment_id" IS 'Mảng kinh doanh'; COMMENT ON COLUMN "account_financial_summary"."partner_id" IS 'Pháp nhân'; COMMENT ON COLUMN "account_financial_summary"."cost_center_id" IS 'Cost center'; COMMENT ON COLUMN "account_financial_summary"."dimension_id" IS 'Chiều phân tích'; COMMENT ON COLUMN "account_financial_summary"."account_id" IS 'Tài khoản hạch toán'; COMMENT ON COLUMN "account_financial_summary"."offset_account_id" IS 'Tài khoản đối ứng'; COMMENT ON COLUMN "account_financial_summary"."currency_id" IS 'Nguyên tệ'; COMMENT ON COLUMN "account_financial_summary"."company_id" IS 'Công ty'; COMMENT ON COLUMN "account_financial_summary"."create_uid" IS 'Created by'; COMMENT ON COLUMN "account_financial_summary"."write_uid" IS 'Last Updated by'; COMMENT ON COLUMN "account_financial_summary"."data_type" IS 'Loại'; COMMENT ON COLUMN "account_financial_summary"."accounting_item" IS 'Khoản mục'; COMMENT ON COLUMN "account_financial_summary"."sub_accounting_item" IS 'Tiểu mục'; COMMENT ON COLUMN "account_financial_summary"."content" IS 'Nội dung'; COMMENT ON COLUMN "account_financial_summary"."in_system" IS 'Có hay không trên hệ thống'; COMMENT ON COLUMN "account_financial_summary"."date" IS 'Ngày'; COMMENT ON COLUMN "account_financial_summary"."note" IS 'Ghi chú'; COMMENT ON COLUMN "account_financial_summary"."amount" IS 'Số tiền'; COMMENT ON COLUMN "account_financial_summary"."create_date" IS 'Created on'; COMMENT ON COLUMN "account_financial_summary"."write_date" IS 'Last Updated on';
ALTER TABLE "dimension_account_rel" ADD FOREIGN KEY ("dimension_id") REFERENCES "account_dimension"("id") ON DELETE cascade;
ALTER TABLE "dimension_account_rel" ADD FOREIGN KEY ("account_id") REFERENCES "account_account"("id") ON DELETE cascade;
ALTER TABLE "account_dimension" ADD FOREIGN KEY ("company_id") REFERENCES "res_company"("id") ON DELETE restrict;
ALTER TABLE "account_dimension" ADD FOREIGN KEY ("create_uid") REFERENCES "res_users"("id") ON DELETE set null;
ALTER TABLE "account_dimension" ADD FOREIGN KEY ("write_uid") REFERENCES "res_users"("id") ON DELETE set null;
ALTER TABLE "account_dimension_value" ADD FOREIGN KEY ("dimension_id") REFERENCES "account_dimension"("id") ON DELETE cascade;
ALTER TABLE "account_dimension_value" ADD FOREIGN KEY ("create_uid") REFERENCES "res_users"("id") ON DELETE set null;
ALTER TABLE "account_dimension_value" ADD FOREIGN KEY ("write_uid") REFERENCES "res_users"("id") ON DELETE set null;
ALTER TABLE "business_segment" ADD FOREIGN KEY ("create_uid") REFERENCES "res_users"("id") ON DELETE set null;
ALTER TABLE "business_segment" ADD FOREIGN KEY ("write_uid") REFERENCES "res_users"("id") ON DELETE set null;
ALTER TABLE "account_financial_summary" ADD FOREIGN KEY ("business_segment_id") REFERENCES "business_segment"("id") ON DELETE set null;
ALTER TABLE "account_financial_summary" ADD FOREIGN KEY ("partner_id") REFERENCES "res_partner"("id") ON DELETE set null;
ALTER TABLE "account_financial_summary" ADD FOREIGN KEY ("cost_center_id") REFERENCES "account_analytic_account"("id") ON DELETE set null;
ALTER TABLE "account_financial_summary" ADD FOREIGN KEY ("dimension_id") REFERENCES "account_dimension"("id") ON DELETE set null;
ALTER TABLE "account_financial_summary" ADD FOREIGN KEY ("account_id") REFERENCES "account_account"("id") ON DELETE set null;
ALTER TABLE "account_financial_summary" ADD FOREIGN KEY ("offset_account_id") REFERENCES "account_account"("id") ON DELETE set null;
ALTER TABLE "account_financial_summary" ADD FOREIGN KEY ("currency_id") REFERENCES "res_currency"("id") ON DELETE set null;
ALTER TABLE "account_financial_summary" ADD FOREIGN KEY ("company_id") REFERENCES "res_company"("id") ON DELETE set null;
ALTER TABLE "account_financial_summary" ADD FOREIGN KEY ("create_uid") REFERENCES "res_users"("id") ON DELETE set null;
ALTER TABLE "account_financial_summary" ADD FOREIGN KEY ("write_uid") REFERENCES "res_users"("id") ON DELETE set null;

-- --- AUDIT LOG: 2026-03-26 02:14:53 ---
CREATE TABLE "account_dimension" (id SERIAL NOT NULL, "company_id" int4 NOT NULL, "create_uid" int4, "write_uid" int4, "name" VARCHAR NOT NULL, "code" VARCHAR, "create_date" timestamp, "write_date" timestamp, PRIMARY KEY(id)); COMMENT ON TABLE "account_dimension" IS 'account.dimension'; COMMENT ON COLUMN "account_dimension"."company_id" IS 'Công ty áp dụng'; COMMENT ON COLUMN "account_dimension"."create_uid" IS 'Created by'; COMMENT ON COLUMN "account_dimension"."write_uid" IS 'Last Updated by'; COMMENT ON COLUMN "account_dimension"."name" IS 'Tên chiều PT'; COMMENT ON COLUMN "account_dimension"."code" IS 'Mã chiều PT'; COMMENT ON COLUMN "account_dimension"."create_date" IS 'Created on'; COMMENT ON COLUMN "account_dimension"."write_date" IS 'Last Updated on';
CREATE TABLE "dimension_account_rel" ("dimension_id" INTEGER NOT NULL,
                                          "account_id" INTEGER NOT NULL,
                                          PRIMARY KEY("dimension_id", "account_id"));
                    COMMENT ON TABLE "dimension_account_rel" IS 'RELATION BETWEEN account_dimension AND account_account';
                    CREATE INDEX ON "dimension_account_rel" ("account_id", "dimension_id");
ALTER TABLE "account_dimension" ADD CONSTRAINT "account_dimension_check_code_uniq" unique(code);
COMMENT ON CONSTRAINT "account_dimension_check_code_uniq" ON "account_dimension" IS 'unique(code)';
CREATE TABLE "account_dimension_value" (id SERIAL NOT NULL, "dimension_id" int4, "create_uid" int4, "write_uid" int4, "code" VARCHAR, "name" VARCHAR NOT NULL, "create_date" timestamp, "write_date" timestamp, PRIMARY KEY(id)); COMMENT ON TABLE "account_dimension_value" IS 'account.dimension.value'; COMMENT ON COLUMN "account_dimension_value"."dimension_id" IS 'Thuộc chiều phân tích'; COMMENT ON COLUMN "account_dimension_value"."create_uid" IS 'Created by'; COMMENT ON COLUMN "account_dimension_value"."write_uid" IS 'Last Updated by'; COMMENT ON COLUMN "account_dimension_value"."code" IS 'Mã'; COMMENT ON COLUMN "account_dimension_value"."name" IS 'Tên giá trị'; COMMENT ON COLUMN "account_dimension_value"."create_date" IS 'Created on'; COMMENT ON COLUMN "account_dimension_value"."write_date" IS 'Last Updated on';
CREATE TABLE "business_segment" (id SERIAL NOT NULL, "create_uid" int4, "write_uid" int4, "name" VARCHAR NOT NULL, "code" VARCHAR NOT NULL, "create_date" timestamp, "write_date" timestamp, PRIMARY KEY(id)); COMMENT ON TABLE "business_segment" IS 'Mảng kinh doanh'; COMMENT ON COLUMN "business_segment"."create_uid" IS 'Created by'; COMMENT ON COLUMN "business_segment"."write_uid" IS 'Last Updated by'; COMMENT ON COLUMN "business_segment"."name" IS 'Tên mảng KD'; COMMENT ON COLUMN "business_segment"."code" IS 'Mã mảng KD'; COMMENT ON COLUMN "business_segment"."create_date" IS 'Created on'; COMMENT ON COLUMN "business_segment"."write_date" IS 'Last Updated on';
ALTER TABLE "business_segment" ADD CONSTRAINT "business_segment_check_code_uniq" unique(code);
COMMENT ON CONSTRAINT "business_segment_check_code_uniq" ON "business_segment" IS 'unique(code)';
CREATE TABLE "account_financial_summary" (id SERIAL NOT NULL, "business_segment_id" int4, "partner_id" int4, "cost_center_id" int4, "dimension_id" int4, "account_id" int4, "offset_account_id" int4, "currency_id" int4, "company_id" int4, "create_uid" int4, "write_uid" int4, "data_type" VARCHAR, "accounting_item" VARCHAR, "sub_accounting_item" VARCHAR, "content" VARCHAR, "in_system" VARCHAR, "date" date, "note" text, "amount" numeric, "create_date" timestamp, "write_date" timestamp, PRIMARY KEY(id)); COMMENT ON TABLE "account_financial_summary" IS 'Tổng hợp dữ liệu tài chính'; COMMENT ON COLUMN "account_financial_summary"."business_segment_id" IS 'Mảng kinh doanh'; COMMENT ON COLUMN "account_financial_summary"."partner_id" IS 'Pháp nhân'; COMMENT ON COLUMN "account_financial_summary"."cost_center_id" IS 'Cost center'; COMMENT ON COLUMN "account_financial_summary"."dimension_id" IS 'Chiều phân tích'; COMMENT ON COLUMN "account_financial_summary"."account_id" IS 'Tài khoản hạch toán'; COMMENT ON COLUMN "account_financial_summary"."offset_account_id" IS 'Tài khoản đối ứng'; COMMENT ON COLUMN "account_financial_summary"."currency_id" IS 'Nguyên tệ'; COMMENT ON COLUMN "account_financial_summary"."company_id" IS 'Công ty'; COMMENT ON COLUMN "account_financial_summary"."create_uid" IS 'Created by'; COMMENT ON COLUMN "account_financial_summary"."write_uid" IS 'Last Updated by'; COMMENT ON COLUMN "account_financial_summary"."data_type" IS 'Loại'; COMMENT ON COLUMN "account_financial_summary"."accounting_item" IS 'Khoản mục'; COMMENT ON COLUMN "account_financial_summary"."sub_accounting_item" IS 'Tiểu mục'; COMMENT ON COLUMN "account_financial_summary"."content" IS 'Nội dung'; COMMENT ON COLUMN "account_financial_summary"."in_system" IS 'Có hay không trên hệ thống'; COMMENT ON COLUMN "account_financial_summary"."date" IS 'Ngày'; COMMENT ON COLUMN "account_financial_summary"."note" IS 'Ghi chú'; COMMENT ON COLUMN "account_financial_summary"."amount" IS 'Số tiền'; COMMENT ON COLUMN "account_financial_summary"."create_date" IS 'Created on'; COMMENT ON COLUMN "account_financial_summary"."write_date" IS 'Last Updated on';
ALTER TABLE "dimension_account_rel" ADD FOREIGN KEY ("dimension_id") REFERENCES "account_dimension"("id") ON DELETE cascade;
ALTER TABLE "dimension_account_rel" ADD FOREIGN KEY ("account_id") REFERENCES "account_account"("id") ON DELETE cascade;
ALTER TABLE "account_dimension" ADD FOREIGN KEY ("company_id") REFERENCES "res_company"("id") ON DELETE restrict;
ALTER TABLE "account_dimension" ADD FOREIGN KEY ("create_uid") REFERENCES "res_users"("id") ON DELETE set null;
ALTER TABLE "account_dimension" ADD FOREIGN KEY ("write_uid") REFERENCES "res_users"("id") ON DELETE set null;
ALTER TABLE "account_dimension_value" ADD FOREIGN KEY ("dimension_id") REFERENCES "account_dimension"("id") ON DELETE cascade;
ALTER TABLE "account_dimension_value" ADD FOREIGN KEY ("create_uid") REFERENCES "res_users"("id") ON DELETE set null;
ALTER TABLE "account_dimension_value" ADD FOREIGN KEY ("write_uid") REFERENCES "res_users"("id") ON DELETE set null;
ALTER TABLE "business_segment" ADD FOREIGN KEY ("create_uid") REFERENCES "res_users"("id") ON DELETE set null;
ALTER TABLE "business_segment" ADD FOREIGN KEY ("write_uid") REFERENCES "res_users"("id") ON DELETE set null;
ALTER TABLE "account_financial_summary" ADD FOREIGN KEY ("business_segment_id") REFERENCES "business_segment"("id") ON DELETE set null;
ALTER TABLE "account_financial_summary" ADD FOREIGN KEY ("partner_id") REFERENCES "res_partner"("id") ON DELETE set null;
ALTER TABLE "account_financial_summary" ADD FOREIGN KEY ("cost_center_id") REFERENCES "account_analytic_account"("id") ON DELETE set null;
ALTER TABLE "account_financial_summary" ADD FOREIGN KEY ("dimension_id") REFERENCES "account_dimension"("id") ON DELETE set null;
ALTER TABLE "account_financial_summary" ADD FOREIGN KEY ("account_id") REFERENCES "account_account"("id") ON DELETE set null;
ALTER TABLE "account_financial_summary" ADD FOREIGN KEY ("offset_account_id") REFERENCES "account_account"("id") ON DELETE set null;
ALTER TABLE "account_financial_summary" ADD FOREIGN KEY ("currency_id") REFERENCES "res_currency"("id") ON DELETE set null;
ALTER TABLE "account_financial_summary" ADD FOREIGN KEY ("company_id") REFERENCES "res_company"("id") ON DELETE set null;
ALTER TABLE "account_financial_summary" ADD FOREIGN KEY ("create_uid") REFERENCES "res_users"("id") ON DELETE set null;
ALTER TABLE "account_financial_summary" ADD FOREIGN KEY ("write_uid") REFERENCES "res_users"("id") ON DELETE set null;

-- --- AUDIT LOG: 2026-03-26 02:17:21 ---
CREATE TABLE "account_dimension" (id SERIAL NOT NULL, "company_id" int4 NOT NULL, "create_uid" int4, "write_uid" int4, "name" VARCHAR NOT NULL, "code" VARCHAR, "create_date" timestamp, "write_date" timestamp, PRIMARY KEY(id)); COMMENT ON TABLE "account_dimension" IS 'account.dimension'; COMMENT ON COLUMN "account_dimension"."company_id" IS 'Công ty áp dụng'; COMMENT ON COLUMN "account_dimension"."create_uid" IS 'Created by'; COMMENT ON COLUMN "account_dimension"."write_uid" IS 'Last Updated by'; COMMENT ON COLUMN "account_dimension"."name" IS 'Tên chiều PT'; COMMENT ON COLUMN "account_dimension"."code" IS 'Mã chiều PT'; COMMENT ON COLUMN "account_dimension"."create_date" IS 'Created on'; COMMENT ON COLUMN "account_dimension"."write_date" IS 'Last Updated on';
CREATE TABLE "dimension_account_rel" ("dimension_id" INTEGER NOT NULL,
                                          "account_id" INTEGER NOT NULL,
                                          PRIMARY KEY("dimension_id", "account_id"));
                    COMMENT ON TABLE "dimension_account_rel" IS 'RELATION BETWEEN account_dimension AND account_account';
                    CREATE INDEX ON "dimension_account_rel" ("account_id", "dimension_id");
ALTER TABLE "account_dimension" ADD CONSTRAINT "account_dimension_check_code_uniq" unique(code);
COMMENT ON CONSTRAINT "account_dimension_check_code_uniq" ON "account_dimension" IS 'unique(code)';
CREATE TABLE "account_dimension_value" (id SERIAL NOT NULL, "dimension_id" int4, "create_uid" int4, "write_uid" int4, "code" VARCHAR, "name" VARCHAR NOT NULL, "create_date" timestamp, "write_date" timestamp, PRIMARY KEY(id)); COMMENT ON TABLE "account_dimension_value" IS 'account.dimension.value'; COMMENT ON COLUMN "account_dimension_value"."dimension_id" IS 'Thuộc chiều phân tích'; COMMENT ON COLUMN "account_dimension_value"."create_uid" IS 'Created by'; COMMENT ON COLUMN "account_dimension_value"."write_uid" IS 'Last Updated by'; COMMENT ON COLUMN "account_dimension_value"."code" IS 'Mã'; COMMENT ON COLUMN "account_dimension_value"."name" IS 'Tên giá trị'; COMMENT ON COLUMN "account_dimension_value"."create_date" IS 'Created on'; COMMENT ON COLUMN "account_dimension_value"."write_date" IS 'Last Updated on';
CREATE TABLE "business_segment" (id SERIAL NOT NULL, "create_uid" int4, "write_uid" int4, "name" VARCHAR NOT NULL, "code" VARCHAR NOT NULL, "create_date" timestamp, "write_date" timestamp, PRIMARY KEY(id)); COMMENT ON TABLE "business_segment" IS 'Mảng kinh doanh'; COMMENT ON COLUMN "business_segment"."create_uid" IS 'Created by'; COMMENT ON COLUMN "business_segment"."write_uid" IS 'Last Updated by'; COMMENT ON COLUMN "business_segment"."name" IS 'Tên mảng KD'; COMMENT ON COLUMN "business_segment"."code" IS 'Mã mảng KD'; COMMENT ON COLUMN "business_segment"."create_date" IS 'Created on'; COMMENT ON COLUMN "business_segment"."write_date" IS 'Last Updated on';
ALTER TABLE "business_segment" ADD CONSTRAINT "business_segment_check_code_uniq" unique(code);
COMMENT ON CONSTRAINT "business_segment_check_code_uniq" ON "business_segment" IS 'unique(code)';
CREATE TABLE "account_financial_summary" (id SERIAL NOT NULL, "business_segment_id" int4, "partner_id" int4, "cost_center_id" int4, "dimension_id" int4, "account_id" int4, "offset_account_id" int4, "currency_id" int4, "company_id" int4, "create_uid" int4, "write_uid" int4, "data_type" VARCHAR, "accounting_item" VARCHAR, "sub_accounting_item" VARCHAR, "content" VARCHAR, "in_system" VARCHAR, "date" date, "note" text, "amount" numeric, "create_date" timestamp, "write_date" timestamp, PRIMARY KEY(id)); COMMENT ON TABLE "account_financial_summary" IS 'Tổng hợp dữ liệu tài chính'; COMMENT ON COLUMN "account_financial_summary"."business_segment_id" IS 'Mảng kinh doanh'; COMMENT ON COLUMN "account_financial_summary"."partner_id" IS 'Pháp nhân'; COMMENT ON COLUMN "account_financial_summary"."cost_center_id" IS 'Cost center'; COMMENT ON COLUMN "account_financial_summary"."dimension_id" IS 'Chiều phân tích'; COMMENT ON COLUMN "account_financial_summary"."account_id" IS 'Tài khoản hạch toán'; COMMENT ON COLUMN "account_financial_summary"."offset_account_id" IS 'Tài khoản đối ứng'; COMMENT ON COLUMN "account_financial_summary"."currency_id" IS 'Nguyên tệ'; COMMENT ON COLUMN "account_financial_summary"."company_id" IS 'Công ty'; COMMENT ON COLUMN "account_financial_summary"."create_uid" IS 'Created by'; COMMENT ON COLUMN "account_financial_summary"."write_uid" IS 'Last Updated by'; COMMENT ON COLUMN "account_financial_summary"."data_type" IS 'Loại'; COMMENT ON COLUMN "account_financial_summary"."accounting_item" IS 'Khoản mục'; COMMENT ON COLUMN "account_financial_summary"."sub_accounting_item" IS 'Tiểu mục'; COMMENT ON COLUMN "account_financial_summary"."content" IS 'Nội dung'; COMMENT ON COLUMN "account_financial_summary"."in_system" IS 'Có hay không trên hệ thống'; COMMENT ON COLUMN "account_financial_summary"."date" IS 'Ngày'; COMMENT ON COLUMN "account_financial_summary"."note" IS 'Ghi chú'; COMMENT ON COLUMN "account_financial_summary"."amount" IS 'Số tiền'; COMMENT ON COLUMN "account_financial_summary"."create_date" IS 'Created on'; COMMENT ON COLUMN "account_financial_summary"."write_date" IS 'Last Updated on';
ALTER TABLE "dimension_account_rel" ADD FOREIGN KEY ("dimension_id") REFERENCES "account_dimension"("id") ON DELETE cascade;
ALTER TABLE "dimension_account_rel" ADD FOREIGN KEY ("account_id") REFERENCES "account_account"("id") ON DELETE cascade;
ALTER TABLE "account_dimension" ADD FOREIGN KEY ("company_id") REFERENCES "res_company"("id") ON DELETE restrict;
ALTER TABLE "account_dimension" ADD FOREIGN KEY ("create_uid") REFERENCES "res_users"("id") ON DELETE set null;
ALTER TABLE "account_dimension" ADD FOREIGN KEY ("write_uid") REFERENCES "res_users"("id") ON DELETE set null;
ALTER TABLE "account_dimension_value" ADD FOREIGN KEY ("dimension_id") REFERENCES "account_dimension"("id") ON DELETE cascade;
ALTER TABLE "account_dimension_value" ADD FOREIGN KEY ("create_uid") REFERENCES "res_users"("id") ON DELETE set null;
ALTER TABLE "account_dimension_value" ADD FOREIGN KEY ("write_uid") REFERENCES "res_users"("id") ON DELETE set null;
ALTER TABLE "business_segment" ADD FOREIGN KEY ("create_uid") REFERENCES "res_users"("id") ON DELETE set null;
ALTER TABLE "business_segment" ADD FOREIGN KEY ("write_uid") REFERENCES "res_users"("id") ON DELETE set null;
ALTER TABLE "account_financial_summary" ADD FOREIGN KEY ("business_segment_id") REFERENCES "business_segment"("id") ON DELETE set null;
ALTER TABLE "account_financial_summary" ADD FOREIGN KEY ("partner_id") REFERENCES "res_partner"("id") ON DELETE set null;
ALTER TABLE "account_financial_summary" ADD FOREIGN KEY ("cost_center_id") REFERENCES "account_analytic_account"("id") ON DELETE set null;
ALTER TABLE "account_financial_summary" ADD FOREIGN KEY ("dimension_id") REFERENCES "account_dimension"("id") ON DELETE set null;
ALTER TABLE "account_financial_summary" ADD FOREIGN KEY ("account_id") REFERENCES "account_account"("id") ON DELETE set null;
ALTER TABLE "account_financial_summary" ADD FOREIGN KEY ("offset_account_id") REFERENCES "account_account"("id") ON DELETE set null;
ALTER TABLE "account_financial_summary" ADD FOREIGN KEY ("currency_id") REFERENCES "res_currency"("id") ON DELETE set null;
ALTER TABLE "account_financial_summary" ADD FOREIGN KEY ("company_id") REFERENCES "res_company"("id") ON DELETE set null;
ALTER TABLE "account_financial_summary" ADD FOREIGN KEY ("create_uid") REFERENCES "res_users"("id") ON DELETE set null;
ALTER TABLE "account_financial_summary" ADD FOREIGN KEY ("write_uid") REFERENCES "res_users"("id") ON DELETE set null;

-- --- AUDIT LOG: 2026-03-26 02:47:21 ---
CREATE TABLE "account_dimension" (id SERIAL NOT NULL, "company_id" int4 NOT NULL, "create_uid" int4, "write_uid" int4, "name" VARCHAR NOT NULL, "code" VARCHAR, "create_date" timestamp, "write_date" timestamp, PRIMARY KEY(id)); COMMENT ON TABLE "account_dimension" IS 'account.dimension'; COMMENT ON COLUMN "account_dimension"."company_id" IS 'Công ty áp dụng'; COMMENT ON COLUMN "account_dimension"."create_uid" IS 'Created by'; COMMENT ON COLUMN "account_dimension"."write_uid" IS 'Last Updated by'; COMMENT ON COLUMN "account_dimension"."name" IS 'Tên chiều PT'; COMMENT ON COLUMN "account_dimension"."code" IS 'Mã chiều PT'; COMMENT ON COLUMN "account_dimension"."create_date" IS 'Created on'; COMMENT ON COLUMN "account_dimension"."write_date" IS 'Last Updated on';
CREATE TABLE "dimension_account_rel" ("dimension_id" INTEGER NOT NULL,
                                          "account_id" INTEGER NOT NULL,
                                          PRIMARY KEY("dimension_id", "account_id"));
                    COMMENT ON TABLE "dimension_account_rel" IS 'RELATION BETWEEN account_dimension AND account_account';
                    CREATE INDEX ON "dimension_account_rel" ("account_id", "dimension_id");
ALTER TABLE "account_dimension" ADD CONSTRAINT "account_dimension_check_code_uniq" unique(code);
COMMENT ON CONSTRAINT "account_dimension_check_code_uniq" ON "account_dimension" IS 'unique(code)';
CREATE TABLE "account_dimension_value" (id SERIAL NOT NULL, "dimension_id" int4, "create_uid" int4, "write_uid" int4, "code" VARCHAR, "name" VARCHAR NOT NULL, "create_date" timestamp, "write_date" timestamp, PRIMARY KEY(id)); COMMENT ON TABLE "account_dimension_value" IS 'account.dimension.value'; COMMENT ON COLUMN "account_dimension_value"."dimension_id" IS 'Thuộc chiều phân tích'; COMMENT ON COLUMN "account_dimension_value"."create_uid" IS 'Created by'; COMMENT ON COLUMN "account_dimension_value"."write_uid" IS 'Last Updated by'; COMMENT ON COLUMN "account_dimension_value"."code" IS 'Mã'; COMMENT ON COLUMN "account_dimension_value"."name" IS 'Tên giá trị'; COMMENT ON COLUMN "account_dimension_value"."create_date" IS 'Created on'; COMMENT ON COLUMN "account_dimension_value"."write_date" IS 'Last Updated on';
CREATE TABLE "business_segment" (id SERIAL NOT NULL, "create_uid" int4, "write_uid" int4, "name" VARCHAR NOT NULL, "code" VARCHAR NOT NULL, "create_date" timestamp, "write_date" timestamp, PRIMARY KEY(id)); COMMENT ON TABLE "business_segment" IS 'Mảng kinh doanh'; COMMENT ON COLUMN "business_segment"."create_uid" IS 'Created by'; COMMENT ON COLUMN "business_segment"."write_uid" IS 'Last Updated by'; COMMENT ON COLUMN "business_segment"."name" IS 'Tên mảng KD'; COMMENT ON COLUMN "business_segment"."code" IS 'Mã mảng KD'; COMMENT ON COLUMN "business_segment"."create_date" IS 'Created on'; COMMENT ON COLUMN "business_segment"."write_date" IS 'Last Updated on';
ALTER TABLE "business_segment" ADD CONSTRAINT "business_segment_check_code_uniq" unique(code);
COMMENT ON CONSTRAINT "business_segment_check_code_uniq" ON "business_segment" IS 'unique(code)';
CREATE TABLE "account_financial_summary" (id SERIAL NOT NULL, "business_segment_id" int4, "partner_id" int4, "cost_center_id" int4, "dimension_id" int4, "account_id" int4, "offset_account_id" int4, "currency_id" int4, "company_id" int4, "create_uid" int4, "write_uid" int4, "data_type" VARCHAR, "accounting_item" VARCHAR, "sub_accounting_item" VARCHAR, "content" VARCHAR, "in_system" VARCHAR, "date" date, "note" text, "amount" numeric, "create_date" timestamp, "write_date" timestamp, PRIMARY KEY(id)); COMMENT ON TABLE "account_financial_summary" IS 'Tổng hợp dữ liệu tài chính'; COMMENT ON COLUMN "account_financial_summary"."business_segment_id" IS 'Mảng kinh doanh'; COMMENT ON COLUMN "account_financial_summary"."partner_id" IS 'Pháp nhân'; COMMENT ON COLUMN "account_financial_summary"."cost_center_id" IS 'Cost center'; COMMENT ON COLUMN "account_financial_summary"."dimension_id" IS 'Chiều phân tích'; COMMENT ON COLUMN "account_financial_summary"."account_id" IS 'Tài khoản hạch toán'; COMMENT ON COLUMN "account_financial_summary"."offset_account_id" IS 'Tài khoản đối ứng'; COMMENT ON COLUMN "account_financial_summary"."currency_id" IS 'Nguyên tệ'; COMMENT ON COLUMN "account_financial_summary"."company_id" IS 'Công ty'; COMMENT ON COLUMN "account_financial_summary"."create_uid" IS 'Created by'; COMMENT ON COLUMN "account_financial_summary"."write_uid" IS 'Last Updated by'; COMMENT ON COLUMN "account_financial_summary"."data_type" IS 'Loại'; COMMENT ON COLUMN "account_financial_summary"."accounting_item" IS 'Khoản mục'; COMMENT ON COLUMN "account_financial_summary"."sub_accounting_item" IS 'Tiểu mục'; COMMENT ON COLUMN "account_financial_summary"."content" IS 'Nội dung'; COMMENT ON COLUMN "account_financial_summary"."in_system" IS 'Có hay không trên hệ thống'; COMMENT ON COLUMN "account_financial_summary"."date" IS 'Ngày'; COMMENT ON COLUMN "account_financial_summary"."note" IS 'Ghi chú'; COMMENT ON COLUMN "account_financial_summary"."amount" IS 'Số tiền'; COMMENT ON COLUMN "account_financial_summary"."create_date" IS 'Created on'; COMMENT ON COLUMN "account_financial_summary"."write_date" IS 'Last Updated on';
ALTER TABLE "dimension_account_rel" ADD FOREIGN KEY ("dimension_id") REFERENCES "account_dimension"("id") ON DELETE cascade;
ALTER TABLE "dimension_account_rel" ADD FOREIGN KEY ("account_id") REFERENCES "account_account"("id") ON DELETE cascade;
ALTER TABLE "account_dimension" ADD FOREIGN KEY ("company_id") REFERENCES "res_company"("id") ON DELETE restrict;
ALTER TABLE "account_dimension" ADD FOREIGN KEY ("create_uid") REFERENCES "res_users"("id") ON DELETE set null;
ALTER TABLE "account_dimension" ADD FOREIGN KEY ("write_uid") REFERENCES "res_users"("id") ON DELETE set null;
ALTER TABLE "account_dimension_value" ADD FOREIGN KEY ("dimension_id") REFERENCES "account_dimension"("id") ON DELETE cascade;
ALTER TABLE "account_dimension_value" ADD FOREIGN KEY ("create_uid") REFERENCES "res_users"("id") ON DELETE set null;
ALTER TABLE "account_dimension_value" ADD FOREIGN KEY ("write_uid") REFERENCES "res_users"("id") ON DELETE set null;
ALTER TABLE "business_segment" ADD FOREIGN KEY ("create_uid") REFERENCES "res_users"("id") ON DELETE set null;
ALTER TABLE "business_segment" ADD FOREIGN KEY ("write_uid") REFERENCES "res_users"("id") ON DELETE set null;
ALTER TABLE "account_financial_summary" ADD FOREIGN KEY ("business_segment_id") REFERENCES "business_segment"("id") ON DELETE set null;
ALTER TABLE "account_financial_summary" ADD FOREIGN KEY ("partner_id") REFERENCES "res_partner"("id") ON DELETE set null;
ALTER TABLE "account_financial_summary" ADD FOREIGN KEY ("cost_center_id") REFERENCES "account_analytic_account"("id") ON DELETE set null;
ALTER TABLE "account_financial_summary" ADD FOREIGN KEY ("dimension_id") REFERENCES "account_dimension"("id") ON DELETE set null;
ALTER TABLE "account_financial_summary" ADD FOREIGN KEY ("account_id") REFERENCES "account_account"("id") ON DELETE set null;
ALTER TABLE "account_financial_summary" ADD FOREIGN KEY ("offset_account_id") REFERENCES "account_account"("id") ON DELETE set null;
ALTER TABLE "account_financial_summary" ADD FOREIGN KEY ("currency_id") REFERENCES "res_currency"("id") ON DELETE set null;
ALTER TABLE "account_financial_summary" ADD FOREIGN KEY ("company_id") REFERENCES "res_company"("id") ON DELETE set null;
ALTER TABLE "account_financial_summary" ADD FOREIGN KEY ("create_uid") REFERENCES "res_users"("id") ON DELETE set null;
ALTER TABLE "account_financial_summary" ADD FOREIGN KEY ("write_uid") REFERENCES "res_users"("id") ON DELETE set null;

-- --- AUDIT LOG: 2026-03-26 04:58:50 ---
CREATE TABLE "account_business_performance" (id SERIAL NOT NULL, "business_segment_id" int4, "partner_id" int4, "cost_center_id" int4, "dimension_id" int4, "account_id" int4, "offset_account_id" int4, "currency_id" int4, "company_id" int4, "create_uid" int4, "write_uid" int4, "data_type" VARCHAR, "accounting_item" VARCHAR, "sub_accounting_item" VARCHAR, "content" VARCHAR, "in_system" VARCHAR, "date" date, "note" text, "amount" numeric, "create_date" timestamp, "write_date" timestamp, PRIMARY KEY(id)); COMMENT ON TABLE "account_business_performance" IS 'Hiệu quả tài chính'; COMMENT ON COLUMN "account_business_performance"."business_segment_id" IS 'Mảng kinh doanh'; COMMENT ON COLUMN "account_business_performance"."partner_id" IS 'Pháp nhân'; COMMENT ON COLUMN "account_business_performance"."cost_center_id" IS 'Cost center'; COMMENT ON COLUMN "account_business_performance"."dimension_id" IS 'Chiều phân tích'; COMMENT ON COLUMN "account_business_performance"."account_id" IS 'Tài khoản hạch toán'; COMMENT ON COLUMN "account_business_performance"."offset_account_id" IS 'Tài khoản đối ứng'; COMMENT ON COLUMN "account_business_performance"."currency_id" IS 'Nguyên tệ'; COMMENT ON COLUMN "account_business_performance"."company_id" IS 'Công ty'; COMMENT ON COLUMN "account_business_performance"."create_uid" IS 'Created by'; COMMENT ON COLUMN "account_business_performance"."write_uid" IS 'Last Updated by'; COMMENT ON COLUMN "account_business_performance"."data_type" IS 'Loại'; COMMENT ON COLUMN "account_business_performance"."accounting_item" IS 'Khoản mục'; COMMENT ON COLUMN "account_business_performance"."sub_accounting_item" IS 'Tiểu mục'; COMMENT ON COLUMN "account_business_performance"."content" IS 'Nội dung'; COMMENT ON COLUMN "account_business_performance"."in_system" IS 'Có hay không trên hệ thống'; COMMENT ON COLUMN "account_business_performance"."date" IS 'Ngày'; COMMENT ON COLUMN "account_business_performance"."note" IS 'Ghi chú'; COMMENT ON COLUMN "account_business_performance"."amount" IS 'Số tiền'; COMMENT ON COLUMN "account_business_performance"."create_date" IS 'Created on'; COMMENT ON COLUMN "account_business_performance"."write_date" IS 'Last Updated on';
ALTER TABLE "account_business_performance" ADD FOREIGN KEY ("business_segment_id") REFERENCES "business_segment"("id") ON DELETE set null;
ALTER TABLE "account_business_performance" ADD FOREIGN KEY ("partner_id") REFERENCES "res_partner"("id") ON DELETE set null;
ALTER TABLE "account_business_performance" ADD FOREIGN KEY ("cost_center_id") REFERENCES "account_analytic_account"("id") ON DELETE set null;
ALTER TABLE "account_business_performance" ADD FOREIGN KEY ("dimension_id") REFERENCES "account_dimension"("id") ON DELETE set null;
ALTER TABLE "account_business_performance" ADD FOREIGN KEY ("account_id") REFERENCES "account_account"("id") ON DELETE set null;
ALTER TABLE "account_business_performance" ADD FOREIGN KEY ("offset_account_id") REFERENCES "account_account"("id") ON DELETE set null;
ALTER TABLE "account_business_performance" ADD FOREIGN KEY ("currency_id") REFERENCES "res_currency"("id") ON DELETE set null;
ALTER TABLE "account_business_performance" ADD FOREIGN KEY ("company_id") REFERENCES "res_company"("id") ON DELETE set null;
ALTER TABLE "account_business_performance" ADD FOREIGN KEY ("create_uid") REFERENCES "res_users"("id") ON DELETE set null;
ALTER TABLE "account_business_performance" ADD FOREIGN KEY ("write_uid") REFERENCES "res_users"("id") ON DELETE set null;
